In [66]:
import numpy as np

import pandas as pd

In [67]:
file_path = 'Transport.csv'
df = pd.read_csv(file_path, header=None)
df = df.applymap(lambda x: int(x) if pd.notna(x) and not np.isinf(x) else x)
print(df.to_string(index=False, header=None))
DF = df.copy()

219 419  28  218    0  151  135  18 120  138 629  84  87  39 514  53  207  193  64   10 182 252  154 247   25  106  382.0
123 373 124  122   96  248   39 114  24  235 533 180 183 135 418 149  111   97 160   86  86 126   58 151   71   10 1536.0
272 522  45  271   53   98  188  35 173   85 682  31  34  14 517   0  260  246  15   63 235 275  257 300   88  159 1011.0
169 419  78  168   50  202   85 680  70  189 579 134 137  89 464 103  157  143 114   40 132 172  104 197   25   56 3580.0
372 622 144  371  152   53  288 134 273   40 782  86  97 113 667  99  360  346 114  162 335 375  307  40  177  259 1048.0
279  45 452  278  424  571  289 442 304  563 205 508 511 463  90 477  267  253 488  414 242 282  270 307  399  318  281.0
345 595 117  344  125   26  261 107 246   13 755  59  70  86 640  72   33  319  87  135 308 348  280 373  150  232 1490.0
 37 287 210   36  182  334   47 200  62  321 447 266 269 221 321 235   25   11 246  172   0  40   28  65  157   76 2012.0
294 544  67  293   75   76  210  57 195   63 704   9  20  36 589  22  282  218  37   85 257 297  229 322  100  181  615.0
 77 303 194   71  166  318   31 184  46  305 463 250 253 205 337 219   65   51 230  156  40  80   12 105  141   60 3140.0
327 577 100  321  108  109  243  90 228   96 737  24  53  69 622  55  315  301  70  118 290 330  262 355  133  214 2297.0
148 398  99  147   71  223   64  89  49  110 558 155 158 110 443 124  136  122 135   61 111 151   83 176   46   35 1877.0
194 444  53  193   25  176  110  43  95  163 604 109 112  74 489  88  182  168  99   15 157 197  129  22    0   81  156.0
237 487  10  231   18  133  153   0 138  120 647  61  69  21 532  35  225  211  46   28 200 240  172 215   43  124  104.0
 99 349 148   98  120  272   15 138   0  259 509 204 207 159 394 173   87   73 184   11  62 102   34 127   95   14  154.0
 61 311 234   12  206  358   71 224  86  345 471 290 293 245 345 259   49   32 270  196  24  64   52  41  181  100 2910.0
643  32 797 1123 1809 1744 1505  89 745 1295 171 210 979 897 313  27 1108 1294 774 1307 156 413 1449 460 2234 1019    NaN

In [68]:
wt_matrix = df.iloc[:-1, :-1].values
df2 = pd.DataFrame(wt_matrix)
print(df2.to_string(index=False, header=None))

219 419  28 218   0 151 135  18 120 138 629  84  87  39 514  53 207 193  64  10 182 252 154 247  25 106
123 373 124 122  96 248  39 114  24 235 533 180 183 135 418 149 111  97 160  86  86 126  58 151  71  10
272 522  45 271  53  98 188  35 173  85 682  31  34  14 517   0 260 246  15  63 235 275 257 300  88 159
169 419  78 168  50 202  85 680  70 189 579 134 137  89 464 103 157 143 114  40 132 172 104 197  25  56
372 622 144 371 152  53 288 134 273  40 782  86  97 113 667  99 360 346 114 162 335 375 307  40 177 259
279  45 452 278 424 571 289 442 304 563 205 508 511 463  90 477 267 253 488 414 242 282 270 307 399 318
345 595 117 344 125  26 261 107 246  13 755  59  70  86 640  72  33 319  87 135 308 348 280 373 150 232
 37 287 210  36 182 334  47 200  62 321 447 266 269 221 321 235  25  11 246 172   0  40  28  65 157  76
294 544  67 293  75  76 210  57 195  63 704   9  20  36 589  22 282 218  37  85 257 297 229 322 100 181
 77 303 194  71 166 318  31 184  46 305 463 250 253 205 337 219  65  51 230 156  40  80  12 105 141  60
327 577 100 321 108 109 243  90 228  96 737  24  53  69 622  55 315 301  70 118 290 330 262 355 133 214
148 398  99 147  71 223  64  89  49 110 558 155 158 110 443 124 136 122 135  61 111 151  83 176  46  35
194 444  53 193  25 176 110  43  95 163 604 109 112  74 489  88 182 168  99  15 157 197 129  22   0  81
237 487  10 231  18 133 153   0 138 120 647  61  69  21 532  35 225 211  46  28 200 240 172 215  43 124
 99 349 148  98 120 272  15 138   0 259 509 204 207 159 394 173  87  73 184  11  62 102  34 127  95  14
 61 311 234  12 206 358  71 224  86 345 471 290 293 245 345 259  49  32 270 196  24  64  52  41 181 100

In [96]:
sum_of_values = np.sum(wt_matrix)

# Print the result
print("Sum of all values in al_matrix:", sum_of_values)

Sum of all values in al_matrix: 90597

In [69]:
demand = df.iloc[-1, :].values
demand = demand[:-1]
demand = demand.astype(int)
print(len(demand))
print(demand)

26
[ 643   32  797 1123 1809 1744 1505   89  745 1295  171  210  979  897
  313   27 1108 1294  774 1307  156  413 1449  460 2234 1019]

In [70]:
supply = df.iloc[:, -1].values
supply = supply[:-1]
supply = supply.astype(int)
print(len(supply))
print(supply)

16
[ 382 1536 1011 3580 1048  281 1490 2012  615 3140 2297 1877  156  104
  154 2910]

In [71]:
if np.sum(supply) == np.sum(demand):
    print("\nTotal Supply equals Total demand")
else:
    print("\nTotal Supply is not equal to total demand")

Total Supply equals Total demand

In [72]:
al_matrix = np.zeros_like(wt_matrix)

# Print the zero matrix
print(al_matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [73]:
def calculate_difference(row_values):
    sorted_values = np.sort(row_values)
    for i in range(len(sorted_values) - 1):
        difference = sorted_values[i + 1] - sorted_values[i]
        if difference != 0:
            return difference
    return 0  # Return the last value if all differences are 0

In [74]:
# Calculate row_pn
row_pn = np.apply_along_axis(calculate_difference, axis=1, arr=wt_matrix)

# Calculate col_pn
col_pn = np.apply_along_axis(calculate_difference, axis=0, arr=wt_matrix)

# Print the results
print("row_pn:", row_pn)
print("col_pn:", col_pn)

row_pn: [10 14 14 15 13 45 13 11 11 19 29 11 15 10 11 12]
col_pn: [ 24 242  18  24  18  27  16  18  24  27 242  15  14   7 231  22   8  21
  22   1  24  24  16  18  25   4]

In [75]:
df['row_pn'] = np.append(row_pn, [0])

# Add col_pn as a new row with zeros for the missing values
df.loc[len(df)] = np.append(col_pn, [0] * (len(df.columns) - len(col_pn)))

In [76]:
print(df.to_string(index=False, header=None))

219 419  28  218    0  151  135  18 120  138 629  84  87  39 514  53  207  193  64   10 182 252  154 247   25  106  382.0 10
123 373 124  122   96  248   39 114  24  235 533 180 183 135 418 149  111   97 160   86  86 126   58 151   71   10 1536.0 14
272 522  45  271   53   98  188  35 173   85 682  31  34  14 517   0  260  246  15   63 235 275  257 300   88  159 1011.0 14
169 419  78  168   50  202   85 680  70  189 579 134 137  89 464 103  157  143 114   40 132 172  104 197   25   56 3580.0 15
372 622 144  371  152   53  288 134 273   40 782  86  97 113 667  99  360  346 114  162 335 375  307  40  177  259 1048.0 13
279  45 452  278  424  571  289 442 304  563 205 508 511 463  90 477  267  253 488  414 242 282  270 307  399  318  281.0 45
345 595 117  344  125   26  261 107 246   13 755  59  70  86 640  72   33  319  87  135 308 348  280 373  150  232 1490.0 13
 37 287 210   36  182  334   47 200  62  321 447 266 269 221 321 235   25   11 246  172   0  40   28  65  157   76 2012.0 11
294 544  67  293   75   76  210  57 195   63 704   9  20  36 589  22  282  218  37   85 257 297  229 322  100  181  615.0 11
 77 303 194   71  166  318   31 184  46  305 463 250 253 205 337 219   65   51 230  156  40  80   12 105  141   60 3140.0 19
327 577 100  321  108  109  243  90 228   96 737  24  53  69 622  55  315  301  70  118 290 330  262 355  133  214 2297.0 29
148 398  99  147   71  223   64  89  49  110 558 155 158 110 443 124  136  122 135   61 111 151   83 176   46   35 1877.0 11
194 444  53  193   25  176  110  43  95  163 604 109 112  74 489  88  182  168  99   15 157 197  129  22    0   81  156.0 15
237 487  10  231   18  133  153   0 138  120 647  61  69  21 532  35  225  211  46   28 200 240  172 215   43  124  104.0 10
 99 349 148   98  120  272   15 138   0  259 509 204 207 159 394 173   87   73 184   11  62 102   34 127   95   14  154.0 11
 61 311 234   12  206  358   71 224  86  345 471 290 293 245 345 259   49   32 270  196  24  64   52  41  181  100 2910.0 12
643  32 797 1123 1809 1744 1505  89 745 1295 171 210 979 897 313  27 1108 1294 774 1307 156 413 1449 460 2234 1019    NaN  0
 24 242  18   24   18   27   16  18  24   27 242  15  14   7 231  22    8   21  22    1  24  24   16  18   25    4    0.0  0

In [77]:
r = c = -1
if np.max(row_pn) >= np.max(col_pn):
    r = np.argmax(row_pn)
elif np.max(row_pn) < np.max(col_pn):
    c = np.argmax(col_pn)

In [78]:
print(df.to_string(index=False, header=None))

219 419  28  218    0  151  135  18 120  138 629  84  87  39 514  53  207  193  64   10 182 252  154 247   25  106  382.0 10
123 373 124  122   96  248   39 114  24  235 533 180 183 135 418 149  111   97 160   86  86 126   58 151   71   10 1536.0 14
272 522  45  271   53   98  188  35 173   85 682  31  34  14 517   0  260  246  15   63 235 275  257 300   88  159 1011.0 14
169 419  78  168   50  202   85 680  70  189 579 134 137  89 464 103  157  143 114   40 132 172  104 197   25   56 3580.0 15
372 622 144  371  152   53  288 134 273   40 782  86  97 113 667  99  360  346 114  162 335 375  307  40  177  259 1048.0 13
279  45 452  278  424  571  289 442 304  563 205 508 511 463  90 477  267  253 488  414 242 282  270 307  399  318  281.0 45
345 595 117  344  125   26  261 107 246   13 755  59  70  86 640  72   33  319  87  135 308 348  280 373  150  232 1490.0 13
 37 287 210   36  182  334   47 200  62  321 447 266 269 221 321 235   25   11 246  172   0  40   28  65  157   76 2012.0 11
294 544  67  293   75   76  210  57 195   63 704   9  20  36 589  22  282  218  37   85 257 297  229 322  100  181  615.0 11
 77 303 194   71  166  318   31 184  46  305 463 250 253 205 337 219   65   51 230  156  40  80   12 105  141   60 3140.0 19
327 577 100  321  108  109  243  90 228   96 737  24  53  69 622  55  315  301  70  118 290 330  262 355  133  214 2297.0 29
148 398  99  147   71  223   64  89  49  110 558 155 158 110 443 124  136  122 135   61 111 151   83 176   46   35 1877.0 11
194 444  53  193   25  176  110  43  95  163 604 109 112  74 489  88  182  168  99   15 157 197  129  22    0   81  156.0 15
237 487  10  231   18  133  153   0 138  120 647  61  69  21 532  35  225  211  46   28 200 240  172 215   43  124  104.0 10
 99 349 148   98  120  272   15 138   0  259 509 204 207 159 394 173   87   73 184   11  62 102   34 127   95   14  154.0 11
 61 311 234   12  206  358   71 224  86  345 471 290 293 245 345 259   49   32 270  196  24  64   52  41  181  100 2910.0 12
643  32 797 1123 1809 1744 1505  89 745 1295 171 210 979 897 313  27 1108 1294 774 1307 156 413 1449 460 2234 1019    NaN  0
 24 242  18   24   18   27   16  18  24   27 242  15  14   7 231  22    8   21  22    1  24  24   16  18   25    4    0.0  0

In [79]:
print(r,c)

-1 1

In [80]:
if r == -1 and c != -1:
    r = np.argmin(wt_matrix[:, c])  

# Check if c is -1 and r is not
elif c == -1 and r != -1:
    c = np.argmin(wt_matrix[r, :])

In [81]:
print(r,c)

5 1

In [82]:
al_matrix[r, c] = wt_matrix[r, c]

In [83]:
df2 = pd.DataFrame(wt_matrix)
print(df2.to_string(index=False, header=None))

219 419  28 218   0 151 135  18 120 138 629  84  87  39 514  53 207 193  64  10 182 252 154 247  25 106
123 373 124 122  96 248  39 114  24 235 533 180 183 135 418 149 111  97 160  86  86 126  58 151  71  10
272 522  45 271  53  98 188  35 173  85 682  31  34  14 517   0 260 246  15  63 235 275 257 300  88 159
169 419  78 168  50 202  85 680  70 189 579 134 137  89 464 103 157 143 114  40 132 172 104 197  25  56
372 622 144 371 152  53 288 134 273  40 782  86  97 113 667  99 360 346 114 162 335 375 307  40 177 259
279  45 452 278 424 571 289 442 304 563 205 508 511 463  90 477 267 253 488 414 242 282 270 307 399 318
345 595 117 344 125  26 261 107 246  13 755  59  70  86 640  72  33 319  87 135 308 348 280 373 150 232
 37 287 210  36 182 334  47 200  62 321 447 266 269 221 321 235  25  11 246 172   0  40  28  65 157  76
294 544  67 293  75  76 210  57 195  63 704   9  20  36 589  22 282 218  37  85 257 297 229 322 100 181
 77 303 194  71 166 318  31 184  46 305 463 250 253 205 337 219  65  51 230 156  40  80  12 105 141  60
327 577 100 321 108 109 243  90 228  96 737  24  53  69 622  55 315 301  70 118 290 330 262 355 133 214
148 398  99 147  71 223  64  89  49 110 558 155 158 110 443 124 136 122 135  61 111 151  83 176  46  35
194 444  53 193  25 176 110  43  95 163 604 109 112  74 489  88 182 168  99  15 157 197 129  22   0  81
237 487  10 231  18 133 153   0 138 120 647  61  69  21 532  35 225 211  46  28 200 240 172 215  43 124
 99 349 148  98 120 272  15 138   0 259 509 204 207 159 394 173  87  73 184  11  62 102  34 127  95  14
 61 311 234  12 206 358  71 224  86 345 471 290 293 245 345 259  49  32 270 196  24  64  52  41 181 100

In [84]:
supply[r]

281

In [85]:
demand[c]

32

In [86]:
if supply[r] > demand[c]:
    supply[r] = supply[r]-demand[c]
    demand[c] = 0
    wt_matrix[:, c] = 1000
elif supply[r] < demand[c]:
    demand[c] = demand[c] - supply[r]
    supply[r] = 0
    wt_matrix[r,:] = 1000
else:
    supply[r] = 0
    demand[c] = 0
    wt_matrix[:, c] = 1000
    wt_matrix[r,:] = 1000

In [87]:
df2 = pd.DataFrame(wt_matrix)
print(df2.to_string(index=False, header=None))

219 1000  28 218   0 151 135  18 120 138 629  84  87  39 514  53 207 193  64  10 182 252 154 247  25 106
123 1000 124 122  96 248  39 114  24 235 533 180 183 135 418 149 111  97 160  86  86 126  58 151  71  10
272 1000  45 271  53  98 188  35 173  85 682  31  34  14 517   0 260 246  15  63 235 275 257 300  88 159
169 1000  78 168  50 202  85 680  70 189 579 134 137  89 464 103 157 143 114  40 132 172 104 197  25  56
372 1000 144 371 152  53 288 134 273  40 782  86  97 113 667  99 360 346 114 162 335 375 307  40 177 259
279 1000 452 278 424 571 289 442 304 563 205 508 511 463  90 477 267 253 488 414 242 282 270 307 399 318
345 1000 117 344 125  26 261 107 246  13 755  59  70  86 640  72  33 319  87 135 308 348 280 373 150 232
 37 1000 210  36 182 334  47 200  62 321 447 266 269 221 321 235  25  11 246 172   0  40  28  65 157  76
294 1000  67 293  75  76 210  57 195  63 704   9  20  36 589  22 282 218  37  85 257 297 229 322 100 181
 77 1000 194  71 166 318  31 184  46 305 463 250 253 205 337 219  65  51 230 156  40  80  12 105 141  60
327 1000 100 321 108 109 243  90 228  96 737  24  53  69 622  55 315 301  70 118 290 330 262 355 133 214
148 1000  99 147  71 223  64  89  49 110 558 155 158 110 443 124 136 122 135  61 111 151  83 176  46  35
194 1000  53 193  25 176 110  43  95 163 604 109 112  74 489  88 182 168  99  15 157 197 129  22   0  81
237 1000  10 231  18 133 153   0 138 120 647  61  69  21 532  35 225 211  46  28 200 240 172 215  43 124
 99 1000 148  98 120 272  15 138   0 259 509 204 207 159 394 173  87  73 184  11  62 102  34 127  95  14
 61 1000 234  12 206 358  71 224  86 345 471 290 293 245 345 259  49  32 270 196  24  64  52  41 181 100

In [88]:
df1 = df.copy()
print(df1.to_string(index=False, header=None))

219 419  28  218    0  151  135  18 120  138 629  84  87  39 514  53  207  193  64   10 182 252  154 247   25  106  382.0 10
123 373 124  122   96  248   39 114  24  235 533 180 183 135 418 149  111   97 160   86  86 126   58 151   71   10 1536.0 14
272 522  45  271   53   98  188  35 173   85 682  31  34  14 517   0  260  246  15   63 235 275  257 300   88  159 1011.0 14
169 419  78  168   50  202   85 680  70  189 579 134 137  89 464 103  157  143 114   40 132 172  104 197   25   56 3580.0 15
372 622 144  371  152   53  288 134 273   40 782  86  97 113 667  99  360  346 114  162 335 375  307  40  177  259 1048.0 13
279  45 452  278  424  571  289 442 304  563 205 508 511 463  90 477  267  253 488  414 242 282  270 307  399  318  281.0 45
345 595 117  344  125   26  261 107 246   13 755  59  70  86 640  72   33  319  87  135 308 348  280 373  150  232 1490.0 13
 37 287 210   36  182  334   47 200  62  321 447 266 269 221 321 235   25   11 246  172   0  40   28  65  157   76 2012.0 11
294 544  67  293   75   76  210  57 195   63 704   9  20  36 589  22  282  218  37   85 257 297  229 322  100  181  615.0 11
 77 303 194   71  166  318   31 184  46  305 463 250 253 205 337 219   65   51 230  156  40  80   12 105  141   60 3140.0 19
327 577 100  321  108  109  243  90 228   96 737  24  53  69 622  55  315  301  70  118 290 330  262 355  133  214 2297.0 29
148 398  99  147   71  223   64  89  49  110 558 155 158 110 443 124  136  122 135   61 111 151   83 176   46   35 1877.0 11
194 444  53  193   25  176  110  43  95  163 604 109 112  74 489  88  182  168  99   15 157 197  129  22    0   81  156.0 15
237 487  10  231   18  133  153   0 138  120 647  61  69  21 532  35  225  211  46   28 200 240  172 215   43  124  104.0 10
 99 349 148   98  120  272   15 138   0  259 509 204 207 159 394 173   87   73 184   11  62 102   34 127   95   14  154.0 11
 61 311 234   12  206  358   71 224  86  345 471 290 293 245 345 259   49   32 270  196  24  64   52  41  181  100 2910.0 12
643  32 797 1123 1809 1744 1505  89 745 1295 171 210 979 897 313  27 1108 1294 774 1307 156 413 1449 460 2234 1019    NaN  0
 24 242  18   24   18   27   16  18  24   27 242  15  14   7 231  22    8   21  22    1  24  24   16  18   25    4    0.0  0

In [89]:
print(supply)

[ 382 1536 1011 3580 1048  249 1490 2012  615 3140 2297 1877  156  104
  154 2910]

In [90]:
print(demand)

[ 643    0  797 1123 1809 1744 1505   89  745 1295  171  210  979  897
  313   27 1108 1294  774 1307  156  413 1449  460 2234 1019]

In [91]:


# Ensure the supply and demand arrays have integer data type
supply = supply.astype(int)
demand = demand.astype(int)

# Update values in rows 0-15 and columns 0-25 from wt_matrix
df.iloc[:16, :26] = wt_matrix[:16, :26]

# Update column 16 from the supply array (update only available elements)
df.iloc[:len(supply), 26] = supply

# Update row 26 from the demand array using a for loop
for i in range( len(demand)):
    df.loc[16, i] = demand[i]

In [92]:
from IPython.display import display, HTML

# Assuming you have a DataFrame named df
# Display the DataFrame df with horizontal scroll
display(HTML(df.to_html()))

In [93]:
df = df.iloc[:-1, :]

# Remove the last column
df = df.iloc[:, :-1]

In [95]:
for i in range(0,3):
    display(HTML(df.to_html()))